version: "{build}"
os: Visual Studio 2015
clone_folder: C:\Projects\MaterialX

environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"

configuration:
    - Release
    
build_script:
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" ..
  - cmake --build . --target install --config %CONFIGURATION%
  - ctest --output-on-failure --build-config %CONFIGURATION%
